language: php

php:
 - 5.6
 - 7.0
 - 7.1
 - 7.2

install:
 - travis_retry composer self-update && composer --version
 - export PATH="$HOME/.composer/vendor/bin:$PATH"
 - COMPOSER_MEMORY_LIMIT=-1 travis_retry composer install --prefer-dist --no-interaction

before_script:
 - php -r "echo INTL_ICU_VERSION . \"\n\";"
 - php -r "echo INTL_ICU_DATA_VERSION . \"\n\";"
 - mysql --version

# initialize database
 - mysql -e 'CREATE DATABASE `yii2seotest`;';
 - php tests/_app/yii migrate/up --interactive=0

# codeception config
 - cp codeception.yml.dist codeception.yml

script:
 - composer validate --no-check-lock
 - vendor/bin/codecept run