language: php

services:
 - mysql

php:
 - 7.2
 - 7.3
 - 7.4

install:
 - travis_retry composer self-update && composer --version
 - export PATH="$HOME/.composer/vendor/bin:$PATH"
 - COMPOSER_MEMORY_LIMIT=-1 travis_retry composer install --prefer-dist --no-interaction

before_script:
 - php -r "echo INTL_ICU_VERSION . \"\n\";"
 - php -r "echo INTL_ICU_DATA_VERSION . \"\n\";"
 - mysql --version

# initialize database
 - mysql -e 'CREATE DATABASE `yii2seotest`;';
 - php tests/_app/yii migrate/up --interactive=0

script:
 - vendor/bin/phpcs --standard=PSR2 src/
 - vendor/bin/phpcs --standard=PSR2 --extensions=php tests/
 - vendor/bin/codecept build
 - vendor/bin/codecept run